
m = int ( input("Введите номер месяца: ") )
if m == 1:  print("январь")
elif m == 2:  print("февраль")    
elif m == 3:  print("март")
elif m == 4:  print("апрель")
elif m == 5:  print("май")
elif m == 6:  
  print("июнь", end="")
  print(", июнь!")         
elif m == 7:  print("июль")
elif m == 8:  print("август")
elif m == 9:  print("сентябрь")
elif m == 10: print("октябрь")
elif m == 11: print("ноябрь")
elif m == 12: print("декабрь")
else: print("ошибка")
